<?php
    /**
     * @param $url : PLINK URL
     * @param $body : Stringify body of the request
     * @param $headers : Array of headers
     */
    function callToPlink($url,$body,$headers){
        $ch = curl_init();
        curl_setopt($ch, CURLOPT_URL,$url);
        curl_setopt($ch, CURLOPT_POST, TRUE);
        curl_setopt($ch, CURLOPT_CUSTOMREQUEST, "POST");
        curl_setopt($ch, CURLOPT_POSTFIELDS, $body);

        curl_setopt($ch, CURLOPT_HEADER, true);
        curl_setopt($ch, CURLOPT_HTTPHEADER, $headers);
        curl_setopt($ch, CURLOPT_FOLLOWLOCATION, true);
        curl_setopt($ch, CURLOPT_RETURNTRANSFER, true);
        curl_setopt($ch, CURLOPT_BINARYTRANSFER, true);
        curl_setopt($ch, CURLOPT_CONNECTTIMEOUT ,0);
        curl_setopt($ch, CURLOPT_TIMEOUT, 60); //timeout in seconds
        if( substr( $url, 0, 5 ) == "https" ){
        curl_setopt($ch, CURLOPT_SSL_VERIFYHOST, 0);
        curl_setopt($ch, CURLOPT_SSL_VERIFYPEER, 0);
        }
        curl_setopt($ch, CURLOPT_VERBOSE, true);
        $retValue = curl_exec($ch);
        $headsize = curl_getinfo($ch, CURLINFO_HEADER_SIZE);
        $headers_ = substr($retValue, 0, $headsize);
        $response = trim(substr($retValue, $headsize));
            if (curl_errno($ch)) {
                throw new \Exception(curl_error($ch));
            }
            curl_close($ch);

        return $response;
    }

    // Datetime when transaction made
    $transaction_time = date("Y-m-d H:i:s").substr((string)microtime(), 1, 6).date(' O');

    // Construct product details
    $product_details=array(
        array(
            "item_code" => "10223",   // Item code generated by merchant's system
            "item_title" => "T-Shirt", // Item title/name
            "quantity" => 3,  // Quantity of product
            "total" => intval(ceil(3*10000)),  // Total amount of product (quantity x price)
            "currency" => "IDR"  // by system
        ),
    );

    // Construct Shipping details
    $shipping_address=[
        "address" => "Jl. Raya Octocat No. 89", // Shipping address
        "telephoneNumber" => "0812345678", // Shipping telephone number
        "handphoneNumber" => "" // Shipping handphone number
    ];

    //other bills. ex. tax
    $other_bills = array(

    );

    //minutes to milliseconds
    $validity = strtotime("+".(1440)." minutes");

    //datenow + $validity in milliseconds
    $validity_formatted = date("Y-m-d H:i:s",$validity).'.000000'.date(' O',$validity);

    $body=[
        "invoice_number"=> 'INV-334444', // Item code generated by merchant's system
        "merchant_id" => '000012000024', // Generated by plink system
        "merchant_key_id" => '0003944444-33343434', // Generated by plink system
        "merchant_ref_no" => 'ORD232323', // Order unique generated by Merchant system (unique)
        "transaction_currency" => "IDR", //must IDR
        "transaction_amount" => intval(ceil(10000)), // round and decimal value  of transaction amount
        "product_details" => json_encode($product_details), // Stringify product details
        "va_name" => "Octocat", // nama pemilik rekening
        "user_name" =>"The Octocat", // nama lengkap
        "user_email" => "octocat@mail.com", // email submit
        "user_phone_number" => "+6",
        "user_id" => "123456789", // user id
        "backend_callback_url" => "http://octocat.com/plink/callback.php", // backend callback url
        "frontend_callback_url" => "http://octocat.com/frontpage.php", // frontend callback url
        "transaction_date_time" => $transaction_time, // datetime when transaction made transaction date time. ex. 2021-01-21 17:08:30.404 +0700
        "transmission_date_time" => date("Y-m-d H:i:s").substr((string)microtime(), 1, 6).date(' O'), // datetime post data made to plink system. ex. 2021-01-21 17:08:30.404 +0700
        "remarks" => "Octocat Payment t-shirt", // order caption
        "user_device_id" => "", //can be set to device id or user agent
        "user_ip_address" => "127.0.0.1", //User ip address
        "shipping_details" => json_encode($shipping_address), //Stringify shipping details
        "payment_method" => "", // Payment method. Keep it blank if u want to show all payment method in payment page
        "other_bills" => json_encode($other_bills),
        "validity"=>$validity_formatted // validity date time after the addition with $validity. ex. 2021-01-21 17:08:30.404 +0700
    ];

    try{
        $url = "https://secure2-staging.plink.co.id/gateway/v2/payment/integration/transaction/api/submit-trx"; // url for of plink system. ex. https://secure2-staging.plink.co.id for staging environment
        $payload = json_encode($body,JSON_UNESCAPED_SLASHES|JSON_PRETTY_PRINT); // Stringify $body
        $key = "ecf3ffdfdfsswe232323"; // secret key generated by plink system
        $token = hash_hmac('sha256', $payload, $key); // generate token using secret key and payload
        $header=array(
            'Content-Type: application/json', // set send content type to json
            'Accept: application/json', // set accept content type response to json
            'mac:'.$token  // set mac header to token
        );
        $response = callToPlink($url,$payload,$header); // call to plink system with params provided $url, $payload and $header
        $result = json_decode($response); // decode response php stdclass

        if($result->response_code === "PL000" || $result->response_code === "MBDD00"){
            /**
             * Handle success response
             * possible response
             * response_code
             * response_message
             * response_description
             * payment_page_url
             * plink_ref_no
             * .. etc
             * You can read in documetion for more detail
             * https://docs.google.com/document/d/1_GTgzzzeFEEl2eiTHSLE4xNE6OAn63b1gTQmvYa7qVE/edit#
             *
             * Important! : Better to record plink_ref_no and use it in your backend system to inqury transaction status
             */

        }else if($result->response_code === "PL032" || $result->response_code === "MBDD32"){
            // if response code is PL032 or MBDD32, then it means that the transaction was submitted before and
            // returning the transaction status
            $desc = $result->response_description;

            if($desc === "transaction exist. Status payment: SETLD"){
                echo "Transaction exist. Status payment: SETLD";
                exit;
            }else if($desc === "transaction exist. Status payment: PNDNG"){
                echo "Transaction exist. Status payment: PNDNG";
                exit;
            }else if($desc === "transaction exist. Status payment: REJEC"){
                echo "transaction exist. Status payment: REJEC";
                exit;
            }else{
                //handle if message resp is not in the list above
                throw new Exception("Something error...");
            }
        }else{
            //handle error
            throw new Exception($result->response_message); // Throw error for duplicate error order
        }
    }catch(\Exception $e){
        echo $e->getMessage(); // Print error message
    }
