<?php
    /**
     * @param $url : PLINK URL
     * @param $body : Stringify body of the request
     * @param $headers : Array of headers
     */
    function callToPlink($url,$body,$headers){
        $ch = curl_init();
        curl_setopt($ch, CURLOPT_URL,$url);
        curl_setopt($ch, CURLOPT_POST, TRUE);
        curl_setopt($ch, CURLOPT_CUSTOMREQUEST, "POST");
        curl_setopt($ch, CURLOPT_POSTFIELDS, $body);

        curl_setopt($ch, CURLOPT_HEADER, true);
        curl_setopt($ch, CURLOPT_HTTPHEADER, $headers);
        curl_setopt($ch, CURLOPT_FOLLOWLOCATION, true);
        curl_setopt($ch, CURLOPT_RETURNTRANSFER, true);
        curl_setopt($ch, CURLOPT_BINARYTRANSFER, true);
        curl_setopt($ch, CURLOPT_CONNECTTIMEOUT ,0);
        curl_setopt($ch, CURLOPT_TIMEOUT, 60); //timeout in seconds
        if( substr( $url, 0, 5 ) == "https" ){
        curl_setopt($ch, CURLOPT_SSL_VERIFYHOST, 0);
        curl_setopt($ch, CURLOPT_SSL_VERIFYPEER, 0);
        }
        curl_setopt($ch, CURLOPT_VERBOSE, true);
        $retValue = curl_exec($ch);
        $headsize = curl_getinfo($ch, CURLINFO_HEADER_SIZE);
        $headers_ = substr($retValue, 0, $headsize);
        $response = trim(substr($retValue, $headsize));
            if (curl_errno($ch)) {
                throw new \Exception(curl_error($ch));
            }
            curl_close($ch);

        return $response;
    }

    $body=[
        "plink_ref_no"=> "123456789", // PLINK reference number got from PLINK
        "merchant_ref_no"=>"ORD232323", // Order unique generated by Merchant system (unique)
        "merchant_key_id"=> "0003944444-33343434", // Generated by plink system
        "merchant_id"=> "000012000024" // Generated by plink system
    ];

    $url = "https://secure2-staging.plink.co.id/gateway/v2/payment/integration/transaction/api/inquiry-transaction"; // url for of plink system. ex. https://secure2-staging.plink.co.id for staging environment
    $payload = json_encode($body,JSON_UNESCAPED_SLASHES|JSON_PRETTY_PRINT); // Stringify $body
    $key = "ecf3ffdfdfsswe232323"; // secret key generated by plink system
    $token = hash_hmac('sha256', $payload, $key); // generate token using secret key and payload
    $header=array(
        'Content-Type: application/json', // set send content type to json
        'Accept: application/json', // set accept content type response to json
        'mac:'.$token  // set mac header to token
    );

    try{
        $response = callToPlink($url,$payload,$header); // call to plink system with params provided $url, $payload and $header
        $result = json_decode($response); // decode response php stdclass
        if(isset($result->response_code)){
            /**
             * Do something like updating payemnt status to database
             *
             */

            if($result->response_code === "PL000" || $result->response_code === "MBDD00"){
                if($result->transaction_status === "SETLD"){
                    echo "Status payment: SETLD";
                    exit;
                }else if($result->transaction_status === "PNDNG"){
                    echo "Status payment: PNDNG";
                    exit;
                }else if($result->transaction_status === "REJEC"){
                    echo "Status payment: REJEC";
                    exit;
                }else{
                    //handle if message resp is not in the  list above
                    throw new Exception("Something error...");
                }
            }else{
                //Log Error
                plink_log("(Call to pg) Admin Inqury Trx: ". print_r($result,true),'error');
                throw new Exception($result->response_message);
            }
        }

    }catch(\Exception $e){
        echo $e->getMessage(); // Print error message
    }