<?php
    // validate request type
    if($_SERVER['REQUEST_METHOD'] === 'GET'){
        echo 'request not for this method is not allowed';
        exit;
    }

    $incomingdata=json_decode(file_get_contents('php://input')); //get body callback send by PLINK system convert to stdclass

    // validate request data and HMAC header
    if(!isset($incomingdata)&&!isset($_SERVER['HTTP_MAC'])){
        echo 'invalid request';
        exit;
    }else{
       try{
            $key = "ecf3ffdfdfsswe232323"; // secret key generated by plink system
            $hmac_generated = hash_hmac('sha256',file_get_contents('php://input'), $key);
            $hmac = $_SERVER['HTTP_MAC']; // get hmac header from PLINK system

            // validate hmac header is empty or null
            if(is_null($hmac) || empty($hmac)){
                throw new Exception("Mac doesn't exist");
            }

            // validate incoming data and HMAC header
            if($hmac != $hmac_generated){
                throw new Exception("Access denied. Invalid Payload");
            }

            // do something like updating payemnt status to database
            if($incomingdata->transaction_status === "SETLD"){
                echo "Status payment: SETLD";
                exit;
            }else if($incomingdata->transaction_status === "PNDNG"){
                echo "Status payment: PNDNG";
                exit;
            }else if($incomingdata->transaction_status === "REJEC"){
                echo "Status payment: REJEC";
                exit;
            }

            // reply to plink server with status 200
            header("HTTP/1.1 200 OK");
       }catch(Exception $e){
           // reply to plink server with status 400
           header("Status: 400 ".$e->getMessage());
           exit;
       }
    }

